version: '3.9'
name: 'rinha-de-backend'

services:
  spring-api1:
    image: localhost/rinhabackend2023:0.0.1-SNAPSHOT
    container_name: spring-api1
    environment:
      - SERVER_PORT=8080
      - db_user=rinha_user
      - db_password=rinha2023
      - db_host=192.168.15.114
    depends_on:
      - postgres-db
    deploy:
      resources:
        limits:
          cpus: '0.55'
          memory: '1GB'

  spring-api2:
    image: localhost/rinhabackend2023:0.0.1-SNAPSHOT
    container_name: spring-api2
    environment:
      - SERVER_PORT=8080
      - db_user=rinha_user
      - db_password=rinha2023
      - db_host=192.168.15.114
    depends_on:
      - postgres-db
    deploy:
      resources:
        limits:
          cpus: '0.55'
          memory: '1GB'

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - spring-api1
      - spring-api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.05'
          memory: '0.1GB'

  postgres-db:
    image: docker.io/library/postgres:15.2-alpine
    container_name: postgres-db
    environment:
      - TZ=America/Sao_Paulo
      - POSTGRES_USER=rinha_user
      - POSTGRES_PASSWORD=rinha2023
      - POSTGRES_DB=rinhadb
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: '0.9GB'